### ISSUE TITLE
Mallet dependency: version missing

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core-examples#13]
Modules lda-asl and wordembeddings-asl do not compile because pom.xml does not specify the Mallet dependency version.

**Comment by reckart** [comment]
Since mallet now depends on a library that is not on Maven Central, I have moved it to the "deps-not-on-maven-central" profile:

https://github.com/dkpro/dkpro-core/commit/d0369ce929c56d934a917a229f20836396f733f5

If you enable that profile during the build, then the version should come in through the import of the DKPro Core ASL POM that you are probably using.

**Comment by carschno** [comment]
With https://github.com/dkpro/dkpro-core/issues/839, this should no longer be necessary.
